version: '3.8'
name: ingesta_opensearch_prod

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: ingesta_opensearch_prod
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - network.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=false
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - http.cors.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: ingesta_opensearch_dashboards_prod
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=YOUR_PASSWORD
    ports:
      - "5601:5601"
    networks:
      - opensearch-net
    depends_on:
      opensearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  sveltekit-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ingesta_sveltekit_app_prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ORIGIN=http://localhost:3000
      - OPENSEARCH_URL=http://opensearch:9200
    ports:
      - "3000:3000"
    networks:
      - opensearch-net
    depends_on:
      opensearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  opensearch-data:
    driver: local

networks:
  opensearch-net:
    driver: bridge